apiVersion: nmstate.io/v1                                                       
kind: NodeNetworkConfigurationPolicy                                            
metadata:                                                                       
  name: slb
spec:
  capture:
    primary-nic: interfaces.description == "primary"
    secondary-nic: interfaces.description == "secondary"
  desiredState:
    interfaces:
    - name: brcnv
      type: ovs-interface
      state: up
      mac-address: "{{ capture.primary-nic.interfaces.0.mac-address }}"
      ipv4:
        enabled: true
        dhcp: true
    - name: brcnv
      type: ovs-bridge
      state: up
      bridge:
        options:
          stp: false
          mcast-snooping-enable: false
          rstp: false
        port:
        - name: bond0
          link-aggregation:
            mode: balance-slb
            port:
            - name: "{{ capture.primary-nic.interfaces.0.name }}"
            - name: "{{ capture.secondary-nic.interfaces.0.name }}"
        - name: brcnv
